"""Render docs/tissue-dictionary.md from mexp.tissue_data (tables) plus the framing prose below.
Run after any change to mexp/tissue_data.py so the document and the data cannot drift."""
from __future__ import annotations

import pathlib

from mexp import tissues as TS
from mexp import tissue_data as TD

OUT = pathlib.Path(__file__).resolve().parents[1] / "docs" / "tissue-dictionary.md"

INTRO = """# Tissue and organ dictionary — MR properties, multi-component structure, and what a voxel really contains

**Version:** 2.2 — 2026-09-09 (verification pass: twelve priority-1 PDFs read; no RECALLED component set remains). Generated by `scripts/render_tissue_dictionary_doc.py` from `mexp/tissue_data.py`; the JSON
release is `data/tissue_dictionary.json`. Companion to charter §1.2 (tissue-level threshold), §4 Phase 0, §6.1 (ground-truth
axis) and gaps register E3. Full citations are in `bibliography.md`.

## 1. Why this dictionary is a strategic component, not a convenience

The project's central question — *how many exponential components can clinical MR data support, and how precisely* — has no
answer without a population of realistic truths. The Phase 0 threshold evaluation showed that the answer at a fixed acquisition
is decided by the **amplitude vector** (the fractions of the components) more than by the placement of the time constants, the
noise model, or whether σ is known. A single myelin-like 20/80 split is one point in that space; the body is a family of very
different points: a dominant short pool with a minor long one (muscle, liver), two comparable pools (marrow, breast), a minor
short pool (grey matter), a well-separated pair with both fractions large (prostate), and genuinely mono-exponential tissues
(myocardium, blood, CSF) that any honest method must report as K = 1.

So the dictionary does five jobs. (1) It is the **ground-truth population** the harness scores every method against — each
entry's composition is a discrete truth with its clinical functional attached (§6.2 functional recovery). (2) It defines **which
functional matters per tissue** (myelin water fraction, luminal water fraction, extracellular fraction, fat fraction, perfusion
fraction), which is what Phase 3's "estimate functionals, not spectra" is scored on. (3) It states, per tissue, **whether
multi-component estimation is even physically posed**: which pools exist, which exchange fast enough to coalesce, which are
invisible to a given echo train — so that a null result in a tissue is understood as physics rather than as a failed method.
(4) It fixes **realistic acquisitions and SNRs per organ**, since a 64-echo prostate protocol and an 8-echo cardiac protocol are
different problems. (5) It is a **release artifact**: an open, cited, machine-readable table of multi-component compositions
does not appear to exist (register E3), and the harness can publish one.

Every number carries a provenance status. As of this version the count of component values is:
"""

THEORY = """
## 2. How many components are "really" there? A framework for a macroscopic voxel

A clinical voxel (1–8 mm³) of any tissue contains water in several physically distinct places, plus non-aqueous protons.
Each place is a candidate exponential component. Four filters stand between that physical count and the number a fit can
recover:

1. **Exchange.** Two pools with relaxation rates R_a, R_b and exchange rate k_ex appear as one component when
   k_ex ≫ |R_a − R_b| (fast exchange), as two when k_ex ≪ |R_a − R_b| (slow exchange), and as a broadened, shifted,
   echo-spacing-dependent pair in between. On the **T2** axis (rates 5–100 s⁻¹) many membrane-limited exchanges
   (residence times 10–500 ms) fall in the slow-to-intermediate regime, so 2–3 apparent components survive. On the **T1**
   axis (rates ≈ 1 s⁻¹) the same exchange is fast, so multi-component T1 is strongly attenuated (white matter's short-T1
   fraction is 8 % at 3 T against a myelin water fraction of 15 %). Blood is the extreme: plasma–erythrocyte exchange
   (~10 ms) is fast even on the T2 axis, so blood is one component whose T2 depends on oxygenation and echo spacing.
2. **Partial volume.** At voxel scale every entry acquires neighbours' pools: CSF for brain and cord, blood for every
   perfused organ, fat for breast, marrow and pancreas, synovial fluid for cartilage. These are real components of the
   *voxel* even when absent from the *tissue*.
3. **Visibility window.** Pools with T2 below the first echo (collagen-bound water ~1–3 ms, macromolecule-associated water
   < 5 ms, cortical-bone bound water ~0.4 ms) are absent from a CPMG train starting at 6–10 ms and present in UTE. The
   harness drops them and renormalises the fractions at evaluation time rather than pretending.
4. **Intra-pool dispersion.** Orientation (magic angle in cartilage and tendon), depth zones, pore-size distributions
   (bone), and oxygenation gradients spread a "component" into a distribution. Past a point the question "how many
   components" stops being well posed and the continuum form of charter §1.2 is the right description — which is why the
   dictionary records a functional for each tissue and not only a K.

The pattern across the table below is consistent: **4–7 physical pools → 2–3 apparent T2 components → 1–2 resolvable at
clinical SNR**, with K = 3 resolvable nowhere at clinical SNR without constraining a component. The per-tissue `theory`
block records the pools, the exchange argument, and the three counts. These counts are reasoned, not measured; they are
the hypotheses the harness is built to test, and the `n_resolvable_clinical_T2` column is what the CRLB evaluation in
`results/threshold_tissues.md` checks.

## 3. Reading the tables

Times in ms; diffusivities in µm²/ms (= 10⁻³ mm²/s); water content and lipid content as mass fractions (Woodard & White
1986 Table I, chemical composition — membrane lipid included); PDFF as the fraction of MR-visible protons that are mobile
triglyceride (what Dixon/IDEAL/MRS measure — the two fat numbers differ by construction: white matter is 18 % lipid by mass and
0 % PDFF); relative proton density with CSF = 1.
Status codes: **PRIMARY** (the paper's own table/text was read), **SECONDARY** (abstract, review table, same-author
conference abstract, or the paper through a publisher-mirrored PDF), **TERTIARY** (textbook/website tabulation),
**RECALLED** (from memory; not opened), **THEORY** (a working configuration derived from physiology, not a measurement).
Ranges are literature ranges where a page gave them, otherwise the spread across the sources named.

"""

CLOSING = """
## 5. Verification status and what moves a row

| Status | Component values | What moves it |
|---|---|---|
| PRIMARY | {PRIMARY} | — (re-check only if the source is corrected) |
| SECONDARY | {SECONDARY} | opening the paper's own table (PDF in `literature/`) → PRIMARY |
| TERTIARY | {TERTIARY} | replacing the website/textbook number with the primary it cites |
| RECALLED | {RECALLED} | opening the named source (the one remaining value is the renal-medulla IVIM D*; no RECALLED *component set* remains as of v2.2) |
| THEORY | {THEORY} | a multi-component relaxometry study of the organ (none reached for liver, spleen, kidney, pancreas in vivo — see §6, *future research project*) — or the harness's own simulator-plus-estimator results marking the split as unsupported; the three CSF partial-volume components of the brain and cord rows are THEORY because the primaries see the > 1 s peak but do not tabulate its voxel fraction |

Bulk properties (water/PD, T1, T2, ADC, lipid, PDFF) carry their own status per value in the tables above. As of v2.2 the
water contents and lipid mass fractions rest on Woodard & White 1986 Table I (PRIMARY) with Whittall 1997 Table 2 for brain,
the abdominal and pelvic T1/T2 columns at both fields on de Bazelaire 2004 Tables 1–2 (PRIMARY), the fat and MSK relaxation
times on Gold 2004 (PRIMARY), the marrow fat fraction on Le Ster 2016 Table 1 (PRIMARY), and every Stanisz 2005 value on
Table 1 of the publisher PDF (PRIMARY; re-read 2026-09-09, no number changed). The component sets of brain WM and GM (Whittall
1997, MacKay 1994), cervical cord (MacMillan 2011), skeletal muscle (Saab 1999, with Araujo 2014 at 3 T), WM T1 (Labadie 2014),
Achilles tendon (Du 2012) and prostate (Sabouri 2017 ×2) were moved to PRIMARY from the papers' own tables in the v2.2 pass;
Reiter 2009, Horch 2010 and Luciani 2008 had been read in full before. PDFF values for lean organs remain RECALLED ranges from
the water–fat imaging literature: none of the 57 PDFs on hand is a water–fat paper for those organs, and the papers that would
settle them are listed in `literature-requests.md` (priority 1b).

## 6. What is missing, by design of the next passes

- **Pathology as a second axis.** Every entry is the normal tissue. The clinically decisive cases are the *changes*: MS
  lesion (myelin water loss), oedematous muscle (extracellular fraction up), steatotic liver (PDFF above the 5.56 % cut-off of
  Szczepaniak 2005, graded ~ 6.4 / 17.4 / 22.1 % by Tang 2013 — a chemically shifted fat pool added to the T2 mixture) and
  iron-loaded liver (T2 collapse), fatty pancreas and fatty infiltration of muscle and myocardium (PDFF up), prostate cancer
  (luminal water fraction down — Sabouri 2017 already gives the row: malignant PZ LWF 0.10 ± 0.05 at 81 / 548 ms against 0.24 in
  nonmalignant PZ), oedematous muscle (Araujo 2014's venous-filling state is a measured surrogate: the long fraction rises from
  8 to 14 % and its T2 from 159 to 181 ms), cartilage degeneration (Reiter's trypsin-degraded row: 64/149 ms, 11/86 %),
  bone-marrow infiltration (fat fraction down), myocardial oedema and fibrosis, MS lesions (MacKay 1994: MWF 4.1–6.4 % against
  15.6 % in normal WM). The schema takes a `condition` field without change; the next dictionary revision adds one pathological
  variant per organ with its own sources, starting with steatotic liver at PDFF 10 and 25 % (charter §10 step 8e).
- **Abdominal multi-component measurements — a future research project, not current focus.** No in vivo multi-component T2
  study of liver, spleen, kidney or pancreas was reached; the splits are THEORY and say so. Measuring them (multi-echo
  relaxometry with IVIM in the same session, so that the T2 and diffusion compartment fractions can be compared) is recorded
  in the gaps register (E3) as a candidate project for later, and the dictionary will take the values when they exist.
- **Organs not yet covered:** lung (very low PD, T2* dominated), skin, placenta, bowel wall, lymph node, testis, brain tumour
  heterogeneity (a continuous-spectrum truth rather than discrete), peripheral nerve, intervertebral disc (two-pool
  nucleus/annulus), fat-water phantoms as the calibration row.
- **Field-strength completeness.** 1.5 T and 3 T are carried; 7 T (MWF rises, T1 lengthens, T2 shortens) and 0.55 T (T1
  shortens — the low-field renaissance) are the two ends the harness should also test.
- **Diffusion beyond scalar/IVIM.** The white-matter standard model and muscle/cardiac tensors are carried as
  compartment sets; the kernel that consumes them (`diffusion_standard_model`, b-tensor kernel) is exercised on the base
  class in tests but not registered (charter G2).
- **Proton density from a quantitative primary.** Water-content numbers now rest on Woodard & White 1986 (chemical
  composition, PRIMARY) with Oros-Peusquens 2019 for brain; the *relative PD* column is still a tertiary table, and Mezer 2013 /
  Volz 2012 / Abbas 2014 (quantitative MR water mapping) remain to be opened to replace it.
"""


def fmt_v(rec) -> str:
    if rec is None:
        return "—"
    v = rec.get("value")
    if v is None:
        s = "n/a"
    elif isinstance(v, float) and v < 10:
        s = f"{v:g}"
    else:
        s = f"{v:g}"
    if rec.get("range"):
        lo, hi = rec["range"]
        s += f" ({lo:g}–{hi:g})"
    return f"{s} `{rec['status']}`"


def entry_section(e: TS.TissueEntry) -> str:
    raw = next(x for x in TD.ENTRIES if x["key"] == e.key)
    P = raw["properties"]
    lines = [f"### {e.tissue} — {e.organ} (`{e.key}`)", ""]
    lines += ["| property | 1.5 T | 3 T | source(s) |", "|---|---|---|---|"]
    wc = P.get("water_content"); pd = P.get("pd_relative_csf"); adc = P.get("ADC")
    lines.append(f"| water content (g/g) | {fmt_v(wc)} | | {wc['source']} |")
    lines.append(f"| proton density (CSF = 1) | {fmt_v(pd)} | | {pd['source']} |")
    T1, T2 = P.get("T1_ms", {}), P.get("T2_ms", {})
    lines.append(f"| T1 (ms) | {fmt_v(T1.get('1.5T'))} | {fmt_v(T1.get('3T'))} | {'; '.join(r['source'] for r in T1.values())} |")
    lines.append(f"| T2 (ms) | {fmt_v(T2.get('1.5T'))} | {fmt_v(T2.get('3T'))} | {'; '.join(r['source'] for r in T2.values())} |")
    lines.append(f"| ADC (µm²/ms) | {fmt_v(adc)} | | {adc['source']} |")
    lm, pdff = P.get("lipid_mass_fraction"), P.get("pdff")
    lines.append(f"| lipid (g/g, chemical) | {fmt_v(lm)} | | {lm['source']} |")
    lines.append(f"| PDFF (MR fat fraction) | {fmt_v(pdff)} | | {pdff['source']} |")
    lines.append("")
    for m, cs in e.component_sets.items():
        lines.append(f"**{m} components** — kernel `{cs.kernel}`, field {cs.field_T} T, set status `{cs.status.value}`; functional: {cs.functional}; "
                     f"typical acquisition: {dict(cs.typical_acquisition)}" + (f". *{cs.note}*" if cs.note else ""))
        lines.append("")
        lines.append("| component | fraction | value | range | status | source |")
        lines.append("|---|---|---|---|---|---|")
        for c in cs.components:
            rng = f"{c.range[0]:g}–{c.range[1]:g}" if c.range else "—"
            note = f" ({c.note})" if c.note else ""
            lines.append(f"| {c.name}{note} | {c.fraction:.3f} | {c.value:g} | {rng} | `{c.status.value}` | {c.source} |")
        lines.append("")
    th = e.theory
    lines.append(f"**What the voxel contains.** {th['n_pools']} physical pools: " + "; ".join(th["pools"]) + ".")
    lines.append("")
    lines.append(f"*Exchange:* {th['exchange']}")
    lines.append("")
    lines.append(f"*Counts:* apparent T2 components {th['n_apparent_T2']}, resolvable at clinical SNR {th['n_resolvable_clinical_T2']} — {th['rationale']}")
    lines.append("")
    lines.append("Sources: " + ", ".join(e.sources) + ".")
    lines.append("")
    return "\n".join(lines)


def main():
    counts = TS.status_summary()
    parts = [INTRO]
    parts.append("| " + " | ".join(counts.keys()) + " |\n|" + "---|" * len(counts) + "\n| " + " | ".join(str(v) for v in counts.values()) + " |\n")
    parts.append(THEORY)
    # overview table
    parts.append("## 4. Overview\n\n| tissue | pools | apparent T2 | resolvable (clinical) | T2 set status | functional |\n|---|---|---|---|---|---|")
    for e in TS.all_entries():
        t2 = e.T2
        parts.append(f"| {e.tissue} ({e.organ}) | {e.theory['n_pools']} | {e.theory['n_apparent_T2']} | {e.theory['n_resolvable_clinical_T2']} | "
                     f"`{t2.status.value if t2 else '—'}` | {t2.functional if t2 else '—'} |")
    parts.append("\n## 4a. Entries\n")
    groups = {}
    for e in TS.all_entries():
        groups.setdefault(e.organ, []).append(e)
    for organ, es in groups.items():
        for e in es:
            parts.append(entry_section(e))
    parts.append(CLOSING.format(**counts))
    parts.append("\n## 7. Source keys\n\n| key | citation (short) |\n|---|---|")
    for k, v in TD.SRC.items():
        parts.append(f"| {k} | {v} |")
    parts.append("\n## 8. Dictionary changelog\n")
    for line in TD.CHANGELOG:
        parts.append(f"- {line}")
    OUT.write_text("\n".join(parts) + "\n")
    print("wrote", OUT, len(OUT.read_text().splitlines()), "lines")


if __name__ == "__main__":
    main()
